const MenuLink = {
  CO_LEARNING: '/co-learning',
  USER_PROFILE: '/user',
  ECOSYSTEM: '/ecosystem',
  ADVOCATE: '/advocate',
  COURSE_MARKET: '/course-market',
  LAUNCH: '/launch-pool',
  EVENTS_PAST: '/events/past',
  PRESS_KIT: '/press-kit',
  PRESS_KIT_ABOUT: '/press-kit/about',
  PRESS_KIT_ARTICLE: '/press-kit/article',
  PRESS_KIT_LOGO: '/press-kit/logo',
  PRESS_KIT_LINK: '/press-kit/link',
  BRAND_KIT: '/brand-kit',
  DOCS: '/docs',
  PARTNERS: '/partners',
  FAUCETS: '/faucets',
  QUEST: '/quest',
  USER_SETTING: '/user/setting',
  HOME: '/home',
  JOB_STATION: '/jobs',
  BLOG: '/blog',
  GLOSSARY: '/glossary',
  EVENTS: '/events',
  LEARNING_TRACK: '/learning-track',
  PRACTICES: '/practices',
  BUILDER_HOME: '/builder-home',
  EXPLORE: '/explore',
  HACKATHON_PROJECTS: '/projects',
  HACKATHON_ORGANIZER: '/organizer',
  MISSION_CENTER: '/mission-center',
  SEARCH: '/search',
} as const

export default MenuLink
